
export const categoryList = [
  {
    id: 1,
    value: 'place',
    label: '🚩Lotes',
  },
  {
    id: 2,
    value: 'house',
    label: '🏠Propiedades',
  },
];

export const ratingList = [
  {
    id: 1,
    value: '1',
    label: '1🌟',
  },
  {
    id: 2,
    value: '2',
    label: '2🌟',
  },
  {
    id: 3,
    value: '3',
    label: '3🌟',
  },
  {
    id: 4,
    value: '4',
    label: '4🌟',
  },
  {
    id: 5,
    value: '5',
    label: '5🌟',
  },
];

export const dataList = [
  {
    id: 1,
    title: 'Casa Barrio Caleuche',
    serviceTime: 'Zona de bosques',
    category: 'house',
    cuisine: 'propiedades',
    rating: 2,
    price: 120000,
    coverSrc: '/Imgs1/foto1.jpeg',
    href: 'Blog01',
  },
  {
    id: 2,
    title: 'Casa en el centro',
    serviceTime: 'Casa de piedra y madera',
    category: 'house',
    cuisine: 'propiedades',
    rating: 3,
    price: 185000,
    coverSrc: '/Imgs2/foto3.jpg',
    href: 'Blog02',
  },
  {
    id: 3,
    title: 'Casa en Vega San martin',
    serviceTime: 'Casa con quincho',
    category: 'house',
    cuisine: 'propiedades',
    rating: 5,
    price: 330000,
    coverSrc: '/Imgs3/miciu1.jpeg',
    href: 'Blog03',
  },
  {
    id: 4,
    title: 'Departamento centríco',
    serviceTime: 'Excelente Inversion',
    category: 'house',
    cuisine: 'propiedades',
    rating: 3,
    price: 145000,
    coverSrc: '/Imgs4/foto16.jpeg',
    href: 'Blog04',
  },
  {
    id: 5,
    title: 'Departamento centríco',
    serviceTime: '3 habitaciones',
    category: 'house',
    cuisine: 'propiedades',
    rating: 3,
    price: 185000,
    coverSrc: '/Imgs5/foto1.jpeg',
    href: 'Blog05',
  },
  {
    id: 6,
    title: 'Cabaña en complejo',
    serviceTime: 'Retasado',
    category: 'house',
    cuisine: 'propiedades',
    rating: 2,
    price: 85000,
    coverSrc: '/Imgs6/foto1.jpeg',
    href: 'Blog06',
  },
  {
    id: 7,
    title: 'Casa en el centro',
    serviceTime: 'Casa en una sola planta',
    category: 'house',
    cuisine: 'propiedades',
    rating: 3,
    price: 160000,
    coverSrc: '/Imgs7/foto1.jpg',
    href: 'Blog07',
  },
  {
    id: 8,
    title: 'Casa en Barrio cerrado',
    serviceTime: 'A 5 km del centro',
    category: 'house',
    cuisine: 'propiedades',
    rating: 5,
    price: 225000,
    coverSrc: '/Imgs9/foto1.jpeg',
    href: 'Blog09',
  },
  {
    id: 9,
    title: 'Inversion ',
    serviceTime: 'Oportunidad',
    category: 'house',
    cuisine: 'inversiones',
    rating: 4,
    price: 160000,
    coverSrc: '/Imgs11/foto1.jpg',
    href: 'Blog10',
  },
  {
    id: 10,
    title: 'Cabaña en complejo',
    serviceTime: 'Retasado',
    category: 'house',
    cuisine: 'propiedades',
    rating: 4,
    price: 140000,
    coverSrc: '/Imgs12/foto4.jpeg',
    href: 'Blog12',
  },
  {
    id: 11,
    title: 'Lote en Alihuen',
    serviceTime: 'Lote plano',
    category: 'place',
    cuisine: 'lotes',
    rating: 3,
    price: 80000,
    coverSrc: '/Imgs13/foto4.jpeg',
    href: 'Blog12',
  },
  {
    id: 12,
    title: 'Excelente inversion',
    serviceTime: 'Oportunidad',
    category: 'place',
    cuisine: 'inversiones',
    rating: 4,
    price: 220000,
    coverSrc: '/Imgs14/foto1.jpg',
    href: 'Blog13',
  },

];
